message("===== Path Check =====")
message("CMAKE_SOURCE_DIR: " ${CMAKE_SOURCE_DIR})
message("CMAKE_BINARY_DIR: " ${CMAKE_BINARY_DIR})
message("CMAKE_INSTALL_PREFIX: " ${CMAKE_INSTALL_PREFIX})
message("DENKO_SRC: " ${DENKO_SRC})
message("======================")
message("===== Build Option Check =====")
message("DENKO_BUILD_SRC: " ${DENKO_BUILD_SRC})
message("DENKO_BUILD_EXAMPLES: " ${DENKO_BUILD_EXAMPLES})
message("==============================")